# SDM660
# Xiaomi
[platina]
rom=lineageos
install_images=recovery

[twolip]
rom=lineageos
install_images=recovery

[whyred]
rom=lineageos
install_images=recovery

[jasmine_sprout]
rom=lineageos
install_images=boot

[jason]
rom=lineageos
install_images=recovery

[lavender]
rom=lineageos
install_images=recovery

[wayne]
rom=lineageos
install_images=recovery

# SDM845
# Xiaomi
[beryllium]
rom=lineageos
install_images=recovery

[polaris]
rom=lineageos
install_images=recovery

# SM6125
# Xiaomi
[laurel_sprout]
rom=evolution-x 
install_images=boot

[ginkgo]
rom=evolution-x 
install_images=boot

# SM8150
# Google
[barbet]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot

[bramble]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot

[redfin]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot

[sunfish]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot

# Oneplus
[hotdog]
rom=evolution-x
install_images=vbmeta, dtbo, recovery

[hotdogb]
rom=evolution-x
install_images=vbmeta, dtbo, recovery

[guacamole]
rom=evolution-x
install_images=vbmeta, dtbo, boot

[guacamoleb]
rom=evolution-x
install_images=vbmeta, dtbo, boot

# SM6375
# Motorola
[ibiza]
rom=lineageos
install_images=dtbo, boot, vendor_boot

# Xiaomi
[veux]
rom=evolution-x 
install_images=boot, vendor_boot, dtbo

# SM8550
# Ayn
[odin2]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[odin2mini]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[odin2portal]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[odin2thor]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[RP6]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
