[ibiza]
rom=lineageos
install_images=dtbo, boot, vendor_boot

[hotdogb]
rom=evolution-x
install_images=vbmeta, dtbo, recovery

[odin2]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[odin2mini]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[odin2portal]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[odin2thor]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot

[rp6]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
