# SDM660
# Xiaomi
[platina]
rom=lineageos
install_images=recovery
oem=xiaomi

[twolip]
rom=lineageos
install_images=recovery
oem=xiaomi

[whyred]
rom=lineageos
install_images=recovery
oem=xiaomi

[jasmine_sprout]
rom=lineageos
install_images=boot
oem=xiaomi

[jason]
rom=lineageos
install_images=recovery
oem=xiaomi

[lavender]
rom=lineageos
install_images=recovery
oem=xiaomi

[wayne]
rom=lineageos
install_images=recovery
oem=xiaomi

# SDM845
# Xiaomi
[beryllium]
rom=lineageos
install_images=recovery
oem=xiaomi

[polaris]
rom=lineageos
install_images=recovery
oem=xiaomi

# SM6125
# Xiaomi
[laurel_sprout]
rom=lineageos
install_images=boot
oem=xiaomi

[ginkgo]
rom=lineageos
install_images=boot
oem=xiaomi

# SM8150
# Google
[barbet]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot
oem=google

[bramble]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot
oem=google

[redfin]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot
oem=google

[sunfish]
rom=evolution-x 
install_images=boot, dtbo, vendor_boot
oem=google

# Oneplus
[hotdog]
rom=evolution-x
install_images=vbmeta, dtbo, recovery
oem=oneplus

[hotdogb]
rom=evolution-x
install_images=vbmeta, dtbo, recovery
oem=oneplus

[guacamole]
rom=evolution-x
install_images=vbmeta, dtbo, boot
oem=oneplus

[guacamoleb]
rom=evolution-x
install_images=vbmeta, dtbo, boot
oem=oneplus

# SM6375
# Motorola
[ibiza]
rom=lineageos
install_images=dtbo, boot, vendor_boot
oem=motorola

# Xiaomi
[veux]
rom=evolution-x 
install_images=boot, vendor_boot, dtbo
oem=xiaomi

# SM8550
# Ayn
[odin2]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
oem=ayn

[odin2mini]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
oem=ayn

[odin2portal]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
oem=ayn

[odin2thor]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
oem=ayn

[RP6]
rom=lineageos
install_images=dtbo, recovery, boot, vendor_boot
oem=ayn
